objects/Callout__mdt.object
<CustomObject>
    <fields>
        <fullName>Auth_Callout_Handler__c</fullName>
        <label>Auth Callout Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auth_Callout__c</fullName>
        <label>Auth Callout</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Base_URL__c</fullName>
        <label>Base URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Callout_Execution__c</fullName>
        <label>Custom Callout Execution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Auth_Callout__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Auth Callout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                    <default>true</default>
                    <label>GET</label>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Path__c</fullName>
        <label>Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Auth_Callout_Validation__c</fullName>
        <label>Pre-Auth Callout Validation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Callout</label>
    <pluralLabel>Callouts</pluralLabel>
</CustomObject>

objects/Callout_Properties__mdt.object
<CustomObject>
    <fields>
        <fullName>Callout__c</fullName>
        <label>Callout</label>
        <referenceTo>Callout__mdt</referenceTo>
        <relationshipLabel>Callouts Properties</relationshipLabel>
        <relationshipName>Callouts_Properties</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Custom_Property__c</fullName>
        <label>Custom Property</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Body</fullName>
                </value>
                <value>
                    <fullName>Header</fullName>
                    <default>true</default>
                    <label>Header</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Callout Properties</label>
    <pluralLabel>Callouts Properties</pluralLabel>
</CustomObject>

classes/CalloutHandler.cls
public with sharing class CalloutHandler {
	
	private String calloutName;
	public String recordWhereClause;
	
	private Callout__mdt calloutMetadata;
	private List<Callout_Properties__mdt> calloutProperties;
	
	public CalloutHandler(String calloutName){
		this.calloutName = calloutName;
		getCalloutInfo();
	}
	
	public CalloutHandler(String calloutName, String recordWhereClause){
		this.calloutName = calloutName;
		this.recordWhereClause = recordWhereClause;
		getCalloutInfo();
	}

    public HttpResponse execute(){
		Http http = new Http();
		HttpRequest request = generateRequest();
		if(String.isNotEmpty(calloutMetadata.Auth_Callout__c)){
			Boolean executeAuthCallout = true;
            
			if(!calloutMetadata.Is_Auth_Callout__c && String.isNotEmpty(calloutMetadata.Pre_Auth_Callout_Validation__c)){
				CalloutInterfaces.PreAuthCalloutValidation calloutValidation = (CalloutInterfaces.PreAuthCalloutValidation) Type.forName(calloutMetadata.Pre_Auth_Callout_Validation__c).newInstance();
				executeAuthCallout = calloutValidation.executeValidation(request);
			}
			if(executeAuthCallout){
				HttpResponse authResponse = new CalloutHandler(calloutMetadata.Auth_Callout__c).execute();
				CalloutInterfaces.AuthCalloutHandler authInterface = (CalloutInterfaces.AuthCalloutHandler) Type.forName(calloutMetadata.Auth_Callout_Handler__c).newInstance();
				authInterface.handleAuthResponse(authResponse, request);
			}
		}
        if(String.isNotEmpty(calloutMetadata.Custom_Callout_Execution__c)){
            CalloutInterfaces.CustomCalloutExecution customExecution = (CalloutInterfaces.CustomCalloutExecution) Type.forName(calloutMetadata.Custom_Callout_Execution__c).newInstance();
			return customExecution.executeCallout(request);
        }
		return http.send(request);
	}
	
	private HttpRequest generateRequest(){
		HttpRequest req = new HttpRequest();
		req.setEndpoint(calloutMetadata.Base_URL__c + calloutMetadata.Path__c);
		req.setMethod(calloutMetadata.Method__c);
        setRequestParameters(req);
		return req;
	}
	
	private void setRequestParameters(HttpRequest req){
		for(Callout_Properties__mdt prop : calloutProperties){
			if(prop.Type__c == 'Header'){
				req.setHeader(prop.Key__c, prop.Value__c);
			}else if(prop.Type__c == 'Body'){
                System.debug(prop.Value__c);
                System.debug(this.recordWhereClause);
				req.setBody(new JSONGeneratorHandler(prop.Value__c, this.recordWhereClause).getJSON());
			}
		}
	}
	
	private void getCalloutInfo(){
		calloutMetadata = Callout__mdt.getInstance(this.calloutName);
		calloutProperties = [SELECT Id, Type__c, Key__c, Value__c, Custom_Property__c FROM Callout_Properties__mdt WHERE Callout__r.DeveloperName = :this.calloutName AND Is_Disabled__c = false];
	}
	
}